### ISSUE TITLE
OpenSky example broken

### ISSUE THREAD

**Issue by jbednar** [holoviz-topics/examples#112]
In https://examples.pyviz.org/opensky there are various warnings that indicate that some library versions need to be updated or pinned, plus a couple of plots where the datashaded content does not appear:
![image](https://user-images.githubusercontent.com/1695496/82993780-c1ae7b80-9fc6-11ea-96c5-3fd11c317c43.png)

**Comment by jbednar** [comment]
Seems to work fine when run with current versions, so probably just needs the anaconda-project.yml file updated.

**Comment by Azaya89** [comment]
This Issue can be closed with this PR #396 I hope.
