### ISSUE TITLE
Voila GPX viewer USGS link dead

### ISSUE THREAD

**Issue by ablythed** [holoviz-topics/examples#177]
Running the next-to-last cell in the Voila GPX viewer notebook for any of the examples gives the following error: `Exception: Cannot retrieve http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N45E006.hgt.zip.` This seems to be a problem with the USGS site and/or the SRTM package.

**Comment by maximlt** [comment]
This example has been removed from this repository.
