### ISSUE TITLE
Formatting of main page

### ISSUE THREAD

**Issue by jbednar** [holoviz-topics/examples#185]
It's all kinds of messed up:
- [ ] Way too much whitespace
- [ ] Why two thumbnails on one row, then another on a new row??  Shouldn't they all be in the same row as each other?
- [ ] Why are titles white on white, visible only on hover? Seems like they should be visible.
- [ ] Tiny thumbnails -- shouldn't they be as big as the space available?
- [ ] Names use initial capitals even for things like IEX Trading that make no sense that way (it's not Lex trading!); same problem found in the titles on each notebook page. Can't we have some way to force correct titles?
- [ ] URL links are crazy, with way too much redundant information; can't we just link like `https://examples.pyviz.org/`*projectname* or at least not have the `#` bit?
 
![image](https://user-images.githubusercontent.com/1695496/131197384-0452ccfb-cd06-40e9-9130-5b02e27fe981.png)
![image](https://user-images.githubusercontent.com/1695496/131197569-0cb6815a-61bf-473f-9e8c-7cd28c8fe6d5.png)

**Comment by maximlt** [comment]
It looks much better now!

<img width="813" alt="image" src="https://github.com/user-attachments/assets/b1d4547a-a2fb-4e3e-9c1b-18f561e212d5">
