### ISSUE TITLE
Gapminders

### ISSUE THREAD

**Issue by maximlt** [holoviz-topics/examples#230]
- [x] Handle the data explicitly instead of loading it dynamically from an external URL directly from the notebook

Given the search I did last summer *Gapminders* was the only project that was downloading data dynamically from a notebook (e.g. `pd.read_csv(external_url)`). It should instead have its data better defined. I'm suggesting adding data as a data source in the `downloads` section of its anaconda-project.yml file. I would also be good to add a small test dataset in `test_data/`.

(If the data isn't heavy at all it could be added to the `/data` subfolder in the project directly).

**Comment by jbednar** [comment]
That all sounds good, thanks!

**Comment by jtao1** [comment]
In my latest PR, I removed downloading from the notebook and added a test dataset.
