### ISSUE TITLE
Project removal suggestion

### ISSUE THREAD

**Issue by maximlt** [holoviz-topics/examples#237]
examples.pyviz.org will move under the HoloViz umbrella. Looking at all the projects, it appears that [voila_gpx_viewer](https://examples.pyviz.org/voila_gpx_viewer/voila_gpx_viewer.html#voila-gpx-viewer-gallery-voila-gpx-viewer) does not depend on any HoloViz libraries. I suggest we remove it.

I also suggest the current authors/maintainers of many examples (@jbednar, @jlstevens and @philippjfr) to have a look at your examples and see whether they should be kept as is, updated or removed (using too old APIs, overlapping too much with other projects, ashamed of it :D, etc.). I think it's important as our plan is to have the gallery as a link in the nav bar of holoviz.org, and have holoviz.org linked from every HoloViz website (cc @droumis). As such, the now pretty much unknown to most PyViz gallery will get more exposure, and even if it's an archive of examples users will still draw inspiration from it.

**Comment by jbednar** [comment]
I don't see any examples that should be removed besides voila-gpx that should move to AE5. I assume that nearly all of them need updating for API and library versions.
