### ISSUE TITLE
Moving to HoloViz

### ISSUE THREAD

**Issue by maximlt** [holoviz-topics/examples#238]
We intend to move this project under the "HoloViz umbrella". I've got a few questions about that move:

- Should the repo move to another GH organization? I think I'd be in favor to move it to the `holoviz` org.
- What should be the new domain name? The current one is `examples.pyviz.org`. The obvious one would be `examples.holoviz.org`, but I guess we could also consider giving it another subdomain name, like `gallery.holoviz.org` or `demo.holoviz.org`. I don't really have an opinion on the alternatives, but others might have! Redirects will need to be setup.
- The projects have their deployment at `https://{servername}.pyviz.demo.anaconda.com`. Can we replace `pyviz` by `holoviz` for new deployments? Or does this depend on some global config of our AE5 instance?

cc @jlstevens @jbednar @droumis

**Comment by jlstevens** [comment]
I think at minimum we should acknowledge that this is not really `pyviz` and use `examples.holoviz.org` domain...

**Comment by jbednar** [comment]
All those suggestions sound good!

**Comment by droumis** [comment]
> Should the repo move to another GH organization? I think I'd be in favor to move it to the holoviz org.

+1

> What should be the new domain name? The current one is examples.pyviz.org. The obvious one would be examples.holoviz.org, but I guess we could also consider giving it another subdomain name, like gallery.holoviz.org or demo.holoviz.org. I don't really have an opinion on the alternatives, but others might have! Redirects will need to be setup.

examples.holoviz.org

**Comment by jlstevens** [comment]
I think we should keep a separate org for the dev tools but there is some sense in having examples on the holoviz org as long as they are interesting to users and worth promoting.

**Comment by maximlt** [comment]
Ok so the actions required to move the project to HoloViz are:

- [ ] Remove the `voila-gpx` project
- [ ] Rebrand the site as HoloViz, updating the logo and a few references from PyViz to HoloViz
- [ ] Add links to holoviz.org (main page and in the navigation bar) and to the HoloViz sites (main page)
- [ ] Move the repo to the `holoviz` org
- [ ] Change the domain name from examples.pyviz.org to examples.holoviz.org, setting up the redirects bits.
- [ ] Link examples.holoviz.org from the navigation bar of holoviz.org, and from wherever it makes sense

There are a few projects that haven't been created by the HoloViz maintainers (e.g. Godbach's comet). I think it'd be fair to ask them if they agree that their contribution is included in this "new" website. Also because we plan to show their Github handle more, at the top of each project page and probably also in the main gallery.

By the way I have noticed that this Github repo has no license, that's funny :) Since it's moving to the `holoviz` org it will certainly have to adopt a project governance, so let's add that to the TODO list:

- [ ] add a license
- [ ] set up the project governance

**Comment by maximlt** [comment]
Hi! If your Github handle is part of the list below, it means you have contributed to an example on this repository :)

- @scottire: genetic_algorithm, particle_swarms
- @djfrancesco: goldbach_comet

I'm sorry to ping you, but I wanted to let you know that the focus of this repository has slightly changed. Its original goal was to host examples demonstrating the usage of any Python visualization tools, the website was hosted at `examples.pyviz.org` and this repository was part of the `pyviz-topics` GitHub organization. It turns out that this project didn't catch much attention and the vast majority of the examples ended up being focused on the HoloViz tools (Panel, HoloViews, hvPlot, Datashader, etc.). We - the HoloViz maintainers - have decided to acknowledge that fact and explicitly limit the scope of the examples contained in this repository to examples that use the HoloViz tools. We have already started this process, hosting the site at `examples.holoviz.org` and renaming the GitHub organization to `holoviz-topics`.

Since the scope of the project has changed, I feel you should have a word to say on whether you want your examples to be part of this "new project"?

**Comment by djfrancesco** [comment]
> Since the scope of the project has changed, I feel you should have a word to say on whether you want your examples to be part of this "new project"?

Hello @maximlt, appreciate your inquiry! If you believe that the goldbach_comet example aligns with the scope of examples on the examples.holoviz.org site, I would be delighted to see it included.

**Comment by maximlt** [comment]
In my opinion `goldbach_comet` aligns with the reduced scope since it uses Datashader :)

**Comment by jbednar** [comment]
Don't all three of them align already, since all of them use and demonstrate HoloViz tools?

**Comment by jlstevens** [comment]
> Don't all three of them align already, since all of them use and demonstrate HoloViz tools?

Have to admit that I was wondering the same thing.

**Comment by maximlt** [comment]
The three of them do and I should have mentioned that! Given the change of org and host name and the lack of license, I thought asking wouldn't hurt :)
