### ISSUE TITLE
Last updated date does not match GitHub last commit date

### ISSUE THREAD

**Issue by ahuang11** [holoviz-topics/examples#374]
Based on https://examples.holoviz.org/gallery/gapminders/gapminders.html, I saw that it was updated yesterday! 
<img width="844" alt="image" src="https://github.com/holoviz-topics/examples/assets/15331990/56e3460b-75e9-43e7-ac29-a76e2ae213d7">

But looking at the GitHub repo, I saw it was updated 5 months ago!
<img width="1281" alt="image" src="https://github.com/holoviz-topics/examples/assets/15331990/5ecdac0c-9925-4bfb-ad2a-8a875dd5e297">

**Comment by maximlt** [comment]
Fixed by https://github.com/holoviz-topics/examples/pull/425
