### ISSUE TITLE
Gerrymandering notebook gives error when running hvplot of shape data cell

### ISSUE THREAD

**Issue by hsparra** [holoviz-topics/examples#410]
On the Gerrymandering notebook, https://examples.holoviz.org/gallery/gerrymandering/gerrymandering.html, I run into an error when I run the cell with:

districts = gdf_districts.hvplot.polygons(geo=True, project=True, color=None)
districts
The error:

DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['Longitude', 'Latitude']

PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html
Has something changed with hvplot since the notebook was created? I am using the shapefile with the same name found on the US Census site. The data does have a geometry column with polygon objects but no Latitude or Longitude columns.

ALL software version info
hvplot 0.10.0
holoviews 1.18.3
bokeh 3.2.2
geopandas 0.14.2
geopandas-base 0.14.2
python 3.12.4

Description of expected behavior and the observed behavior
Observed behavior: See above
Expected behavior: shapes of US congressional districts displayed

Note: The error also occurs on the **hvplot** Geographical Data notebook: https://hvplot.holoviz.org/user_guide/Geographic_Data.html# 

@droumis

**Comment by droumis** [comment]
I just did a fresh install of the gerrymandering example and I cannot reproduce your error.  Did you follow the [getting started instructions](https://examples.holoviz.org/getting_started.html) for the examples?

**Comment by hsparra** [comment]
I ran it on an environment I had with all the packages. It runs find with python 3.10. Must be something related to python 3.12.

Closing since you cannot reproduce.

**Comment by hsparra** [comment]
Closing since others could not reproduce.
