### ISSUE TITLE
Fix nyc_taxi

### ISSUE THREAD

**Issue by droumis** [holoviz-topics/examples#415]
The map is missing and the background color is wrong:

We previously used stamen terrain tiles, but stamen tiles are not yet available. Start by making the bgcolor white and use the map tiles in the second image below

![image](https://github.com/user-attachments/assets/c6bf2bef-2b68-4d36-90c1-cc98a1c4e8ba)

use bgcolor = 'black' or use a darker map tiles option

![image](https://github.com/user-attachments/assets/2ecb54b8-3143-451b-a99f-6b8c18a1410b)

The panel dashboard notebook on nyc_taxi looks good:

![image](https://github.com/user-attachments/assets/a88cf8fc-1f60-453e-81de-43650701d843)

**Comment by maximlt** [comment]
On the first one, we picked a `grey` background in https://github.com/holoviz-topics/examples/pull/370/files#diff-592788e03885bcbe5731eb7f599f40ff5e2d0058bcc1510a573aa2b850851c59R437, I'm not sure why we did that, let's just revert to `white` :)

On the second one, previously we used `tiles = StamenTerrain().redim.range(x=x_range, y=y_range)` but Stamen tiles are not longer available (I think you've got to pay now). Grabbing a screenshot from their website, this is how they look:
![image](https://github.com/user-attachments/assets/10d5097e-7cdb-44c2-a8c1-482232da3767)

**Comment by Azaya89** [comment]
OK. I will incorporate this fix into the #412 PR
