### ISSUE TITLE
Run notebook fails on attractors example

### ISSUE THREAD

**Issue by kdheepak** [holoviz-topics/examples#421]
I tried the run notebook link on this page:

https://examples.holoviz.org/gallery/attractors/attractors_panel.html

And got this error:

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/8bdacd20-0312-4a0b-9937-2d266504056d">

**Comment by maximlt** [comment]
Hi @kdheepak,
I just ran that notebook successfully, are you sure you ran all the previous cells?
![image](https://github.com/user-attachments/assets/961575df-c73c-4900-a560-4457e9d64272)

**Comment by kdheepak** [comment]
My bad! I thought it was a typo where `params` was used instead of `param`.
