### ISSUE TITLE
Shorten the URLS for examples

### ISSUE THREAD

**Issue by jbednar** [holoviz-topics/examples#91]
The URLs that are generated for our examples are quite long and highly redundant.  When there is only one item, the URL contains the project name four times (!):

https://examples.pyviz.org/bay_trimesh/bay_trimesh.html#bay-trimesh-gallery-bay-trimesh

For multiple targets in the same project, there is slightly less redundancy, but still there's no convenient link to pass around:

https://examples.pyviz.org/attractors/attractors.html#attractors-gallery-attractors
https://examples.pyviz.org/attractors/attractors_panel.html#attractors-gallery-attractors-panel
https://examples.pyviz.org/attractors/clifford_panel.html#attractors-gallery-clifford-panel

In each case the part after "#" can be omitted, but users may not know that, and in any case it's annoying to have to delete it.  

Ideally, we could just pass around (and e.g. link to from other sites) the directory name (https://examples.pyviz.org/bay_trimesh or https://examples.pyviz.org/attractors), which is a convenient and readable URL without any redundant information.  However, at the moment such URLs give a 404 (not found) error.

I propose that:
- [x] Visiting the directory should go to the .html page matching the directory name (bay_trimesh.html or attractors.html)
- [x] Ideally, the directory-based URL would be the canonical URL (i.e. what shows up in the address bar), regardless of whether the URL is visited using the html link or the directory. That is, both https://examples.pyviz.org/bay_trimesh and https://examples.pyviz.org/bay_trimesh/bay_trimesh.html should both work (to preserve any existing links), and both of them should show the URL https://examples.pyviz.org/bay_trimesh in the address bar.
- [x] The part after # be deleted from links (no idea where that's coming from, but it seems like it would never be useful)

**Comment by Azaya89** [comment]
I think this issue can be closed now as the website links now work as suggested.
