### ISSUE TITLE
Add human names and dates to all projects

### ISSUE THREAD

**Issue by jbednar** [holoviz-topics/examples#92]
Each of the examples on this site was created by a particular person at a particular time, and there is no expectation that the site maintainers will be updating those examples indefinitely into the future. To make that clear and to properly attribute the projects to their authors, the notebooks and web pages should all have authorship and a date (either first created or last updated, not sure; maybe both?) clearly and visibly indicated.

**Comment by ablythed** [comment]
- [ ] Remove title on each example page on website

For one sample notebook:
- [ ] Add title ("# Title'), author and date (created and last updated) in first cell
- [ ] Remove any extra title-like cells
- [ ] Check that tab title is still correct

Once that notebook works, do it for all the rest.
