### ISSUE TITLE
Issues with attractors_panel

### ISSUE THREAD

**Issue by jbednar** [holoviz-topics/examples#93]
The attractors_panel notebook works well generally, but it has a few open issues:

- [x] 1. Saving to a filename only works if that file already exists on disk.  Looks like I already created an issue for this years ago, but it's still a problem: https://github.com/holoviz/param/issues/304
- [x] 2. If the "+" button is selected (speeding up the player) or the N is increased (slowing down the player) or a slow machine is used, hitting Play can cause drawing/update events to be generated faster than they can be completed. The display can then lag behind the controls in a confusing way, and hitting Stop appears not to have an effect (though it will eventually stop once the queue of events has been consumed). It would be nice to be able configure the player to drop outstanding events when adding new ones, so that it skips ahead rather than getting a confusing backlog. 
- [x] 3. There is too much code in attractors_panel.ipynb.  In practice classes like these would be defined in a .py file, and it would be nice to make this file illustrate good practice in splitting code between notebooks and Python modules, by moving the non-GUI code into a module and showing how the notebook works well for GUI construction.  We'd need to be able to link to the Python file from the notebook where appropriate.
- [x] 4. The Player widgets look very different (and worse) in the rendered HTML page at https://examples.pyviz.org/attractors/attractors_panel.html than they do in Jupyter or in deployed notebooks; much larger and solid colors rather than rounded buttons, and overlapping the subsequent text. Problem with CSS in Sphinx or nbsite?
- [x] 5. The web page https://examples.pyviz.org/attractors/attractors_panel.html used to render the equations, but currently only shows the ASCII source for them, even though similar (?) equations work on https://examples.pyviz.org/attractors/attractors.html

**Comment by jbednar** [comment]
Point 3 is addressed by https://github.com/pyviz-topics/examples/pull/94 . 

Point 5 seems to be working fine today after shift-reloading the page; we'll see if there continue to be issues. The equations still briefly render the ASCII text, but then reformat into the typeset equations.

**Comment by jbednar** [comment]
To illustrate problem #4:
![image](https://user-images.githubusercontent.com/1695496/74477125-53f39f00-4e70-11ea-934a-b0afb29e44ad.png)

**Comment by Azaya89** [comment]
Based on #381, would you say these bugs have been addressed? @jbednar

**Comment by jbednar** [comment]
Good thing to check! I checked the above criteria against the version at https://examples.holoviz.org/gallery/attractors/attractors_panel.html and deployed at https://attractors.holoviz-demo.anaconda.com/attractors_panel . What I found was:

1. The support for saving and loading to a file seems to have disappeared entirely, so I can't check whether new files work. Seems like the object that has the filename parameter is no longer being displayed? Not sure how that got missed in the updates. 
![Image](https://github.com/user-attachments/assets/f2cf3b7d-da05-4a9b-ae4b-6411817557c5) 
2. Pressing Play doesn't seem to do anything at all at https://attractors.holoviz-demo.anaconda.com/attractors_panel, even if I greatly reduce the number of points. The progress bar moves, but the display never updates.
3. Was addressed earlier; done.
4. Seems to have been avoided by no longer showing the app in the web page; no idea if it still has that problem.
5. Fixed!

So it doesn't quite seem functional yet...

**Comment by maximlt** [comment]
> The support for saving and loading to a file seems to have disappeared entirely, so I can't check whether new files work. Seems like the object that has the filename parameter is no longer being displayed? Not sure how that got missed in the updates.

Hmm that's an issue we [flagged early in the review](https://github.com/holoviz-topics/examples/pull/381#issuecomment-2066909990) but then got lost. Reviewing these large multi-notebooks examples isn't easy.

I have a fix in preparation, which also fixes that:

> Pressing Play doesn't seem to do anything at all at https://attractors.holoviz-demo.anaconda.com/attractors_panel, even if I greatly reduce the number of points. The progress bar moves, but the display never updates.

---

>  If the "+" button is selected (speeding up the player) or the N is increased (slowing down the player) or a slow machine is used, hitting Play can cause drawing/update events to be generated faster than they can be completed. The display can then lag behind the controls in a confusing way, and hitting Stop appears not to have an effect (though it will eventually stop once the queue of events has been consumed). It would be nice to be able configure the player to drop outstanding events when adding new ones, so that it skips ahead rather than getting a confusing backlog.

When testing locally I found the behavior to be much better, even after speeding it up a lot (clicking many times on "+"), stopping the player almost immediately stopped the rendering.  

---

> Seems to have been avoided by no longer showing the app in the web page; no idea if it still has that problem.

What would you prefer to see between?

1. An image of attractor (current state)
2. The app (transformed as it now uses a template and we can't display templated apps in a notebook/on the site)

**Comment by jbednar** [comment]
Glad to hear you have a fix for the Play button behavior! Look forward to seeing that.

> What would you prefer to see between?

I don't mind anything about the current approach of not showing the app in the notebook rendering; no problem. My only concern is whether the original issue of the player buttons being poorly rendered on the website still remains, which would apply to any other Player widgets, not just this one example. Based on the Panel website the rendering looks ok, so I'm inclined to consider the Player issue completed:
![Image](https://github.com/user-attachments/assets/8f80c10a-5d34-4977-a3e8-bcc81ea6d00f)
